# .github/workflows/docker-publish.yml
name: Build and Push Docker Image

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/docker-publish.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker image
      run: |
        IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$IMAGE_NAME:latest ./app
        docker push ghcr.io/$IMAGE_NAME:latest
